---

- name: Ensure Packages are installed
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: True
    validate_certs: false
  vars:
    packages:
      - http://yum.postgresql.org/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm
      - postgresql96-server
      - postgresql96
      - python-psycopg2
  become: yes
  become_user: root

- find:
    paths: /var/lib/pgsql/9.6/data/
    patterns: "*.conf"
  register: dir_files
  become: yes
  become_user: root

- command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
  when: dir_files.matched|int == 0
  become: yes
  become_user: root

- name: Generate pg_hba.conf
  template:
    src: pg_hba.conf
    dest: /var/lib/pgsql/9.6/data/pg_hba.conf
  become: yes
  become_user: postgres

- name: Start postgresql
  service:
    name: postgresql-9.6
    enabled: yes
    state: started
  become: yes
  become_user: root