---

- name: Ensure Packages are installed
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: True
    validate_certs: false
  vars:
    packages:
      - nginx
  become: yes
  become_user: root