---

- hosts: all
  roles:
    - { role: common,           tags: [common] }
    - { role: ansible-user,     tags: [common] }

- hosts: jenkins-master
  roles:
    - { role: java,             tags: [jenkins] }
    - { role: jenkins,          tags: [jenkins] }

- hosts: jenkins-slave
  roles:
    - { role: java,             tags: [jenkins] }
    - { role: docker,           tags: [jenkins] }

- hosts: nexus
  roles:
    - { role: java,             tags: [nexus] }
    - { role: docker,           tags: [nexus] }
    - { role: nexus,            tags: [nexus] }

- hosts: sonarqube
  roles:
    - { role: java,             tags: [sonarqube] }
    - { role: postgresql,       tags: [sonarqube] }
    - { role: sonarqube,        tags: [sonarqube] }