---

- name: Enable 2212
  firewalld:
    port: 2212/tcp
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  become: yes
  become_user: root

- name: Disable ssh
  firewalld:
    service: ssh
    permanent: yes
    state: disabled
    immediate: yes
    zone: public
  become: yes
  become_user: root