---

- name: Create jenkins User
  user:
    name: jenkins
    password: "{{jenkins.password | password_hash('sha512', 'mysecretsalt') }}"
    generate_ssh_key: true
    groups:
     - docker
  become: yes
  become_user: root

- name: Remove Docker Images
  cron:
    name: "clean_docker"
    special_time: "daily"
    job: "docker rm $(docker ps -a -q); docker rmi $(docker images -q)"
  become: yes
  become_user: root