---

- name: Create jenkins User
  user:
    name: jenkins
    password: "{{jenkins.password | password_hash('sha512', 'mysecretsalt') }}"
    generate_ssh_key: true
    groups:
     - docker
  become: yes
  become_user: root