---

- name: Create nexus User
  user:
    name: nexus
    password: "{{nexus.password | password_hash('sha512', 'mysecretsalt')}}"
    groups:
      - docker
  become: yes
  become_user: root

- name: "Status file /home/nexus/{{nexusapp.version}}-unix.tar.gz"
  stat:
    path:  "/home/nexus/{{nexusapp.version}}-unix.tar.gz"
  register: nexus_status
  become: yes
  become_user: root

- name: "Download {{nexusapp.version}}-unix.tar.gz"
  get_url:
    url: "https://sonatype-download.global.ssl.fastly.net/repository/repositoryManager/3/{{nexusapp.version}}-unix.tar.gz"
    dest: "/home/nexus/{{nexusapp.version}}-unix.tar.gz"
    mode: 0440
  become: yes
  become_user: nexus
  when: not nexus_status.stat.exists

- name: "Extract {{nexusapp.version}}-unix.tar.gz into /home/nexus"
  unarchive:
    src: "/home/nexus/{{nexusapp.version}}-unix.tar.gz"
    dest: /home/nexus
    remote_src: True
  become: yes
  become_user: nexus
  when: not nexus_status.stat.exists

- name: "Link {{nexusapp.version}} to nexus-current"
  file:
    state: link
    path: /home/nexus/nexus-current
    src: "/home/nexus/{{nexusapp.version}}"
  become: yes
  become_user: nexus

- name: Generate Service Conf
  template:
    src: service.j2
    dest: /etc/systemd/system/nexus.service
    mode: 0744
  become: yes
  become_user: root

- name: Start Nexus
  service:
    name: nexus
    enabled: yes
    state: started
  become: yes
  become_user: root

- name: Generate NGinx Conf
  template:
    src: nginx.j2
    dest: /etc/nginx/conf.d/nexus.conf
    mode: 0744
  become: yes
  become_user: root
  notify: Restart nginx services