---

- name: Enable HTTPS
  firewalld:
    service: https
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  become: yes
  become_user: root


- name: Disable HTTPS
  firewalld:
    service: http
    permanent: yes
    state: disabled
    immediate: yes
    zone: public
  become: yes
  become_user: root

- name: Disable dhcpv6-client
  firewalld:
    service: dhcpv6-client
    permanent: yes
    state: disabled
    immediate: yes
    zone: public
  become: yes
  become_user: root

- name: Disable 2375
  firewalld:
    port: 2375/tcp
    permanent: yes
    state: disabled
    immediate: yes
    zone: public
  become: yes
  become_user: root